### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by ened** [edelabar/NibLoadedView#1]
When including the files into my project, these error messages appear:

Overriding instance method parameter of type 'NSCoder' with implicitly unwrapped optional type 'NSCoder!'
Overriding instance method optional result type 'AnyObject?' with implicitly unwrapped optional type 'AnyObject!'

It was fixed by changing the `awakeAfterUserCoder` methods signature to:

```
    public override func awakeAfterUsingCoder(aDecoder: NSCoder) -> AnyObject? {
```

**Comment by edelabar** [comment]
Can you create a pull request? I'll merge it so you get the contribution.
